export const cities = [
  { label: 'Paris', value: 'Paris' },
  { label: 'Marseille', value: 'Marseille' },
  { label: 'Lyon', value: 'Lyon' },
  { label: 'Toulouse', value: 'Toulouse' },
  { label: 'Nice', value: 'Nice' },
  { label: 'Nantes', value: 'Nantes' },
  { label: 'Strasbourg', value: 'Strasbourg' },
  { label: 'Montpellier', value: 'Montpellier' },
  { label: 'Bordeaux', value: 'Bordeaux' },
  { label: 'Lille', value: 'Lille' },
  { label: 'Rouen', value: 'Rouen' },
  { label: 'Brest', value: 'Brest' },
  { label: 'Grenoble', value: 'Grenoble' },
  { label: 'Tours', value: 'Tours' },
  { label: 'Clermont-Ferrand', value: 'Clermont-Ferrand' },
  { label: 'Orléans', value: 'Orléans' },
  { label: 'Saint-Étienne', value: 'Saint-Étienne' },
  { label: 'Dijon', value: 'Dijon' },
  { label: 'Metz', value: 'Metz' },
  { label: 'Rennes', value: 'Rennes' },
  { label: 'Toulon', value: 'Toulon' },
  { label: 'Limoges', value: 'Limoges' },
  { label: 'Perpignan', value: 'Perpignan' },
  { label: 'Caen', value: 'Caen' },
  { label: 'Annecy', value: 'Annecy' },
  { label: 'Le Mans', value: 'Le Mans' },
  { label: 'Nîmes', value: 'Nîmes' },
  { label: 'Aix-en-Provence', value: 'Aix-en-Provence' },
];
