name: CI - Build, Test & Lint (Dev)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Tests (Jest)
        run: npm test

      - name: Verify Expo build
        run: npx expo export
